version : "3.9"
services:
  flask-api:
    image: wajju786/flask-micro-api:latest
    container_name: flask-micro-api
    ports:
       - "5000:5000"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
